insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.jwt.issuer', 'http://evo.com', '发行人 [Default http://evo.com]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.jwt.signing-key', 'ec9f563404c511e9b8790a151ed9f971', '签名', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.jwt.expiration-time', '1440', '访问令牌过期时间 单位分钟 [Default 60 * 24 * 1]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.jwt.refresh-expiration-time', '4320', '刷新令牌过期时间 单位分钟 [Default 60 * 24 * 3]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.jwt.old-expiration-time', '30', '新令牌期间，旧令牌作为临时过渡令牌的过期时间 单位秒 [Default 30]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.path.login', '/ui/comm/login', '登录页面', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.path.excludes', '/auth/username-password/login, /auth/mobile-number/verify-code, /oauth2/oauth/token', '排除访问控制URI数组', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.verify-code.expiration-time', '2', '过期时间 单位分钟 [Default 2]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.verify-code.type', 'random', 'random 随机; fix 固定 [Default random]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.verify-code.length', '6', '当 type = random 时，验证码位数 [Default 6]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.verify-code.value', '123456', '当 type= fix 时，验证码值，[Default 123456]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.authorization.service-id', 'evo-oauth2', '认证服务的spring.application.name [Default evo-oauth2]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.iam.service-id', 'evo-sys', '提供身份识别与访问管理服务的spring.application.name [Default evo-sys]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.iam.user-details.username-uri', '/user/username', '通过用户登录名获取用户信息的 HTTP REST URI [Default /user/username]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.iam.user-details.mobile-number-uri', '/user/mobile-number', '通过手机获取用户信息的 HTTP REST URI [Default /user/mobile-number]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.iam.user-details.update-login-info-uri', '/user/login-info', '更新登录用户信息的 HTTP REST URI [Default /user/login-info]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.auth.iam.rbac.uri', '/permission/check', '校验权限的 HTTP REST URI [Default /permission/check]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.hibernate.dialect', 'org.hibernate.dialect.MySQLDialect', '数据库方言 [Default org.hibernate.dialect.MySQLDialect]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.hibernate.show-sql', 'true', '是否显示SQL [Default true]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.hibernate.format-sql', 'false', '是否格式化SQL [Default false]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.hibernate.packages', 'com.ritoinfo.framework.evo.sp.demo', '扫描实体包 [Default com.ritoinfo.framework.evo.sp.demo]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.rabbitmq.addresses', '192.168.204.131:5672', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.rabbitmq.host', '192.168.204.131', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.rabbitmq.port', '5672', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.rabbitmq.virtual-host', 'evo_vhost', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.rabbitmq.username', 'evo', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.rabbitmq.password', 'evo', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.redis.company-prefix', 'ZBKG', '公司前缀 [Default EVO]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.redis.cluster.nodes', '192.168.204.132:7001, 192.168.204.132:7002, 192.168.204.132:7003, 192.168.204.132:7004, 192.168.204.132:7005, 192.168.204.132:7006', 'Redis集群', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.ribbon.NFLoadBalancerRuleClassName', 'com.netflix.loadbalancer.RoundRobinRule', '负载均衡策略', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.password.strength', '10', 'BCrypt强哈希函数强度。强度参数越大，散列密码所需的工作(以指数形式)就越多 [Default 10]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.session.user-context.enabled', 'true', '可以通过SessionHolder.getUserContext()获取当前用户 [Default true]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.sms.enabled', 'false', 'true 开启; false 关闭 [Default false]', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.zuul.auth.client.id', 'client_1', 'OAuth2 表oauth_client_details.client_id', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.zuul.auth.client.secret', 'secret_1', 'OAuth2 表oauth_client_details.client_secret', '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.framework.datasource.url', 'jdbc:mysql://192.168.204.130:3306/evo_framework?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.framework.datasource.username', 'evo_framework', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.framework.datasource.password', 'evo_framework', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.demo.datasource.url', 'jdbc:mysql://192.168.204.130:3306/evo_demo?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.demo.datasource.username', 'evo_demo', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.demo.datasource.password', 'evo_demo', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.sys.datasource.url', 'jdbc:mysql://192.168.204.130:3306/evo_sys?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.sys.datasource.username', 'evo_sys', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.sys.datasource.password', 'evo_sys', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.datadict.datasource.url', 'jdbc:mysql://192.168.204.130:3306/evo_datadict?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.datadict.datasource.username', 'evo_datadict', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.datadict.datasource.password', 'evo_datadict', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.activiti.datasource.url', 'jdbc:mysql://192.168.204.130:3306/evo_activiti?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.activiti.datasource.username', 'evo_activiti', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'default', 'evo.activiti.datasource.password', 'evo_activiti', null, '1', now(), '1', now());

insert into config_properties values (null, 'master', 'evo', 'blue', 'evo.rabbitmq.addresses', '192.168.1.9:5672', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'blue', 'evo.rabbitmq.host', '192.168.1.9', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'blue', 'evo.redis.cluster.nodes', '192.168.1.9:7001, 192.168.1.9:7002, 192.168.1.9:7003, 192.168.1.9:7004, 192.168.1.9:7005, 192.168.1.9:7006', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'blue', 'evo.framework.datasource.url', 'jdbc:mysql://192.168.1.9:3306/evo_framework?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'blue', 'evo.demo.datasource.url', 'jdbc:mysql://192.168.1.9:3306/evo_demo?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'blue', 'evo.sys.datasource.url', 'jdbc:mysql://192.168.1.9:3306/evo_sys?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'blue', 'evo.datadict.datasource.url', 'jdbc:mysql://192.168.1.9:3306/evo_datadict?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'blue', 'evo.activiti.datasource.url', 'jdbc:mysql://192.168.1.9:3306/evo_activiti?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true', null, '1', now(), '1', now());

insert into config_properties values (null, 'master', 'evo', 'desktop', 'evo.rabbitmq.addresses', '192.168.18.132:5672', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'desktop', 'evo.rabbitmq.host', '192.168.18.132', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'desktop', 'evo.redis.cluster.nodes', '192.168.18.129:7001, 192.168.18.129:7002, 192.168.18.129:7003, 192.168.18.129:7004, 192.168.18.129:7005, 192.168.18.129:7006', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'desktop', 'evo.framework.datasource.url', 'jdbc:mysql://192.168.18.130:3306/evo_framework?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'desktop', 'evo.demo.datasource.url', 'jdbc:mysql://192.168.18.130:3306/evo_demo?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'desktop', 'evo.sys.datasource.url', 'jdbc:mysql://192.168.18.130:3306/evo_sys?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'desktop', 'evo.datadict.datasource.url', 'jdbc:mysql://192.168.18.130:3306/evo_datadict?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'desktop', 'evo.activiti.datasource.url', 'jdbc:mysql://192.168.18.130:3306/evo_activiti?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true', null, '1', now(), '1', now());

insert into config_properties values (null, 'master', 'evo', 'yqjr', 'evo.rabbitmq.addresses', '10.20.133.40:5672, 10.20.133.43:5672', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'yqjr', 'evo.rabbitmq.host', '10.20.133.43', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'yqjr', 'evo.rabbitmq.port', '5672', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'yqjr', 'evo.rabbitmq.virtual-host', 'vhost_eco', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'yqjr', 'evo.rabbitmq.username', 'eco', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'yqjr', 'evo.rabbitmq.password', 'eco', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'yqjr', 'evo.redis.cluster.nodes', '10.20.133.85:7000, 10.20.133.85:7001, 10.20.133.85:7002, 10.20.133.85:7003, 10.20.133.85:7004, 10.20.133.85:7005', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'yqjr', 'evo.sms.enabled', 'true', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'yqjr', 'evo.sms.address', 'http://10.21.111.71:9087/smserver/submitMessage', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'yqjr', 'evo.sms.comCode', 'ZBKG', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'yqjr', 'evo.sms.orgCode', '00000000', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'yqjr', 'evo.sms.businessNo', 'ZBKG00000000DJCFAPP001', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'yqjr', 'evo.sms.businessTypeCode', '04', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'yqjr', 'evo.sms.channel', '0', null, '1', now(), '1', now());
insert into config_properties values (null, 'master', 'evo', 'yqjr', 'evo.sms.ip', '10.20.133.30', null, '1', now(), '1', now());

insert into zuul_route values (null, 'evo-auth', '/auth/**', 'evo-auth', null, '1', null, null, '1', null, '1', now(), '1', now());
insert into zuul_route values (null, 'evo-oauth2', '/oauth2/**', 'evo-oauth2', null, '1', null, null, '1', null, '1', now(), '1', now());



