server:
  port: ${port:20105}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
spring:
  rabbitmq:
    addresses: ${evo.rabbitmq.addresses}
    host: ${evo.rabbitmq.host}
    port: ${evo.rabbitmq.port}
    virtual-host: ${evo.rabbitmq.virtual-host}
    username: ${evo.rabbitmq.username}
    password: ${evo.rabbitmq.password}
  redis:
    cluster:
      nodes: ${evo.redis.cluster.nodes}
    password: sinosoft
  jackson:
    time-zone: GMT+8
  sleuth:
    sampler:
      probability: 1.0
    http:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  zipkin:
    #    base-url: http://127.0.0.1:9411
    sender:
      type: rabbit
    locator:
      discovery:
        enabled: true
    enabled: true
evo:
  session:
    user-context:
      enabled: false
zipkin:
  rabbitmq:
    queue: zipkin