server:
  port: 20105
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
spring:
  rabbitmq:
    addresses: ${evo.spring.rabbitmq.addresses}
    host: ${evo.spring.rabbitmq.host}
    port: ${evo.spring.rabbitmq.port}
    virtual-host: ${evo.spring.rabbitmq.virtual-host}
    username: ${evo.spring.rabbitmq.username}
    password: ${evo.spring.rabbitmq.password}
  redis:
    cluster:
      nodes: ${evo.spring.redis.cluster.nodes}
  jackson:
    time-zone: GMT+8
  sleuth:
    http:
      enabled: true
    sampler:
      probability: 1.0
evo:
  common:
    session:
      enabled: false
