server:
  port: 20120
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
spring:
  datasource:
    url: ${evo.datadict.datasource.url}
    username: ${evo.datadict.datasource.username}
    password: ${evo.datadict.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 600000
      maximum-pool-size: 60
      max-lifetime: 1800000
      minimum-idle: 10
      read-only: false
  rabbitmq:
    addresses: ${evo.rabbitmq.addresses}
    host: ${evo.rabbitmq.host}
    port: ${evo.rabbitmq.port}
    virtual-host: ${evo.rabbitmq.virtual-host}
    username: ${evo.rabbitmq.username}
    password: ${evo.rabbitmq.password}
  redis:
    cluster:
      nodes: ${evo.redis.cluster.nodes}
  cache:
    redis:
      time-to-live: 3600s
      use-key-prefix: false
  jackson:
    time-zone: GMT+8
  sleuth:
    http:
      enabled: true
    sampler:
      probability: 1.0
mybatis:
  type-aliases-package: com.ritoinfo.framework.evo.sp.datadict.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
