server:
  port: 9411
# 最佳实践：springcloud应用都要指定application.name
spring:
  application:
    name: springcloud-zipkin-server
    main:
      allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://192.168.144.128:3306/zipkin?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 30000 # 等待连接池分配连接的最大时长
      idle-timeout: 600000 # 连接闲置状态的最大时长
      maximum-pool-size: 60 # 连接池中允许的最大连接数, 推荐的公式：((core_count * 2) + effective_spindle_count)
      max-lifetime: 1800000 # 连接的生命时长, 建议设置比数据库超时时长少30秒
      minimum-idle: 10
      read-only: false # 连接只读数据库时配置为true, 保证安全
eureka:
  client:
    serviceUrl: # 指定服务注册中心的地址
      defaultZone: http://localhost:20000/eureka/ # 上面是eureka单机注册中心。下面是eureka集群模式
      # defaultZone: http://admin:123456@eureka2:8001/eureka/,http://admin:123456@eureka3:8002/eureka/,http://admin:123456@eureka2:8003/eureka/
#指明使用mysql存储
zipkin:
  collector:
    rabbitmq:
      # RabbitMQ server address list (comma-separated list of host:port)
      addresses: ${RABBIT_ADDRESSES:192.168.144.128:5672}
      concurrency: ${RABBIT_CONCURRENCY:1}
      # TCP connection timeout in milliseconds
      connection-timeout: ${RABBIT_CONNECTION_TIMEOUT:60000}
      password: ${RABBIT_PASSWORD:ydcx$111}
      queue: ${RABBIT_QUEUE:zipkin}
      username: ${RABBIT_USER:Guosd}
      virtual-host: ${RABBIT_VIRTUAL_HOST:evo-vhost}
      useSsl: ${RABBIT_USE_SSL:false}
  storage:
    type: mysql
    mysql:
      jdbc-url: jdbc:mysql://192.168.144.128:3306/zipkin?useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: root
      password: root
management:
  metrics:
    web:
      server:
        auto-time-requests: false