server:
  port: 20115
  address: ${evo.server.address}
spring:
  rabbitmq:
    host: ${evo.spring.rabbitmq.host}
    port: ${evo.spring.rabbitmq.port}
    virtual-host: ${evo.spring.rabbitmq.virtual-host}
    username: ${evo.spring.rabbitmq.username}
    password: ${evo.spring.rabbitmq.password}
  redis:
    cluster:
      nodes: ${evo.spring.redis.cluster.nodes}
  cache:
    redis:
      time-to-live: 3600s
      use-key-prefix: false
  jackson:
    time-zone: GMT+8
  sleuth:
    http:
      enabled: true
    sampler:
      probability: 1.0
  boot:
    admin:
      client:
        url: ${evo.spring.boot.admin.client.url}
        instance:
          prefer-ip: true
