server:
  port: ${port:20130}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
spring:
  datasource:
    url: ${evo.flowable.datasource.url}
    username: ${evo.flowable.datasource.username}
    password: ${evo.flowable.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 600000
      maximum-pool-size: 60
      max-lifetime: 1800000
      minimum-idle: 10
      read-only: false
  rabbitmq:
    addresses: ${evo.rabbitmq.addresses}
    host: ${evo.rabbitmq.host}
    port: ${evo.rabbitmq.port}
    virtual-host: ${evo.rabbitmq.virtual-host}
    username: ${evo.rabbitmq.username}
    password: ${evo.rabbitmq.password}
  jackson:
    time-zone: GMT+8
  sleuth:
    http:
      enabled: true
    sampler:
      probability: 1.0
  main:
    allow-bean-definition-overriding: true
flowable:
  check-process-definitions: false
  content:
    storage:
      root-folder: flowable/content
  process:
    async:
      executor:
        default-async-job-acquire-wait-time-in-millis: 10000 # 轮询间隔10秒
        max-async-jobs-due-per-acquisition: 1 # 每次抓取1条记录
