@startuml

actor 用户 order 10
participant 第三方应用 order 20
participant 认证服务 order 30
database 资源服务 order 40

用户 -> 第三方应用: 用户使用[第三方应用]
第三方应用 -> 用户: 要求[用户]给予授权
用户 -> 第三方应用: 用户同意授权
第三方应用 -> 认证服务: 使用获得的授权，申请令牌
认证服务 -> 第三方应用: 确认无误后，同意发放令牌
第三方应用 -> 资源服务: 使用令牌，申请资源
资源服务 -> 第三方应用: 确认令牌无误后，同意开放资源

@enduml
