@startuml
事务生产者 -> 事务管理中心: 发送事务生产者准备日志
事务生产者 -> RocketMQ: 发送事务准备消息
事务生产者 -> 事务生产者: 处理本地事务
事务生产者 -> RocketMQ: 发送事务生产者确认消息
事务生产者 -> 事务管理中心: 发送事务确认日志

RocketMQ -> 事务消费者: 接收消息
事务消费者 -> 事务管理中心: 发送事务消费者准备日志
事务消费者 -> 事务消费者: 处理本地事务
事务消费者 -> 事务管理中心: 发送事务消费者确认日志
事务消费者 -> RocketMQ: 响应消息

事务管理中心 -> 事务管理中心: 轮询异常日志

事务管理中心 -> 通知平台: 发现异常及时通知

@enduml
