server:
  port: 20025
  address: ${evo.server.address}
spring:
  datasource:
    url: ${evo.sp.activiti.datasource.url}
    username: ${evo.sp.activiti.datasource.username}
    password: ${evo.sp.activiti.datasource.password}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 600000
      maximum-pool-size: 60
      max-lifetime: 1800000
      minimum-idle: 10
      read-only: false
  rabbitmq:
    host: ${evo.spring.rabbitmq.host}
    port: ${evo.spring.rabbitmq.port}
    virtual-host: ${evo.spring.rabbitmq.virtual-host}
    username: ${evo.spring.rabbitmq.username}
    password: ${evo.spring.rabbitmq.password}
  jackson:
    time-zone: GMT+8
  sleuth:
    http:
      enabled: true
    sampler:
      probability: 1.0
  boot:
    admin:
      client:
        url: ${evo.spring.boot.admin.client.url}
        instance:
          prefer-ip: true
  activiti:
    database-schema: evo_activiti # 数据库名称
    database-schema-update: none # 如果设置为 true， 数据库中没有表时会新建
    check-process-definitions: false # 是否检测流程定义文件
    async-executor-activate: false
    async-executor-enabled: false
