server:
  port: ${port:20005}
spring:
  application:
    name: evo-admin
eureka:
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:20000/eureka
---
spring:
  profiles: sit
eureka:
  instance:
    hostname: ${spring.application.name}-service
  client:
    service-url:
      defaultZone: http://evo-eureka-service:20000/eureka

