server:
  port: ${port:20010}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
spring:
  application:
    name: evo-config
  profiles:
    active: jdbc
  datasource:
    url: jdbc:mysql://192.168.18.134:3306/evo_framework?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: evo_framework
    password: evo_framework
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 600000
      maximum-pool-size: 60
      max-lifetime: 1800000
      minimum-idle: 10
      read-only: false
  rabbitmq:
    addresses: 192.168.18.132:5672
    host: 192.168.18.132
    port: 5672
    virtual-host: evo_vhost
    username: evo
    password: evo
  cloud:
    config:
      server:
        default-label: master
        jdbc:
          sql: select t.key_, t.value from config_property t where t.application = ? and t.profile = ? and t.label = ?
    bus:
      trace:
        enabled: true # 消息总线跟踪开关
eureka:
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5 # 心跳间隔5秒
    health-check-url-path: /actuator/health
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:20000/eureka
---
spring:
  profiles: sit
  datasource:
    url: jdbc:mysql://10.21.127.29:3306/evo_framework?useUnicode=true&characterEncoding=UTF8&useSSL=false
  rabbitmq:
    addresses: 10.21.127.29:5672
    host: 10.21.127.29
eureka:
  client:
    service-url:
      defaultZone: http://evo-eureka-service:20000/eureka
---
spring:
  profiles: blue
  datasource:
    url: jdbc:mysql://192.168.204.130:3306/evo_framework?useUnicode=true&characterEncoding=UTF8&useSSL=false
  rabbitmq:
    host: 192.168.204.131
