server:
  port: 20005
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
spring:
  application:
    name: evo-config
  profiles:
    active: jdbc
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/evo_framework?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: evo_framework
    password: evo_framework
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 600000
      maximum-pool-size: 60
      max-lifetime: 1800000
      minimum-idle: 10
      read-only: false
  rabbitmq:
    addresses: 127.0.0.1:5672
    host: 127.0.0.1
    port: 5672
    virtual-host: evo_vhost
    username: evo
    password: evo
  cloud:
    config:
      server:
        default-label: master
        jdbc:
          sql: select t.key_, t.value from config_properties t where t.application = ? and t.profile = ? and t.label = ?
    bus:
      trace:
        enabled: true # 消息总线跟踪开关
eureka:
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    health-check-url-path: /actuator/health
  client:
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:20000/eureka
---
spring:
  profiles: vm
eureka:
  instance:
    ip-address: 192.168.204.134
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.204.134:50101/eureka
