server:
  port: 20005
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: [actuator, auditevents, autoconfig, beans, conditions, configprops, flyway, heapdump, health, httptrace, info, jolokia, liquibase, logfile, loggers, mappings, metrics, prometheus, scheduledtasks, sessions, shutdown, threaddump, trace]
spring:
  application:
    name: evo-config
eureka:
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    health-check-url-path: /actuator/health
  client:
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:50101/eureka
---
spring:
  profiles:
    active: native
---
spring:
  profiles:
    active: subversion
  cloud:
    config:
      server:
        svn:
          uri: https://apptestaf.faf.com.cn/svn/SVN_faf/SVN_faf_scfw
          username: yanglei
          password: yanglei
          default-label: /src/evo-config-file
---
spring:
  profiles: prod
  boot:
    admin:
      client:
        url: http://10.20.168.48:20020, http://10.20.168.49:20020
eureka:
  instance:
    ip-address: ${parasitifer-ip}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://10.20.168.46:50101/eureka, http://10.20.168.47:50101/eureka
---
spring:
  profiles: uat
eureka:
  instance:
    ip-address: 10.20.133.30
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://10.20.133.30:50101/eureka
---
spring:
  profiles: sit
  boot:
    admin:
      client:
        url: http://10.20.133.30:20020
        instance:
          prefer-ip: true
eureka:
  instance:
    ip-address: 10.20.133.30
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://10.20.133.30:50101/eureka
---
spring:
  profiles: dev
eureka:
  instance:
    ip-address: 10.20.133.30
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://10.20.133.30:50101/eureka
---
spring:
  profiles: dev
eureka:
  instance:
    ip-address: 10.20.133.30
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://10.20.133.30:50101/eureka
---
spring:
  profiles: home
  boot:
    admin:
      client:
        url: http://192.168.1.24:20020
        instance:
          prefer-ip: true
eureka:
  instance:
    ip-address: 192.168.1.24
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.1.24:50101/eureka
