server:
  port: 20010
  tomcat:
    max-threads: 128
    min-spare-threads: 64
spring:
  application:
    name: evo-zuul
  jackson:
    time-zone: GMT+8
zuul:
  retryable: true
  sensitiveHeaders:
  ignoredServices: '*'
  routes:
    evo-sp-auth:
      path: /auth/**
    evo-sp-sys:
      path: /sys/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    evo-sp-auth:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    evo-sp-sys:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
evo-sp-auth:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
evo-sp-sys:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
feign:
  httpclient:
    connection-timeout: 10000
