server:
  port: 50001
  tomcat:
    max-threads: 128
    min-spare-threads: 64
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: [actuator, auditevents, autoconfig, beans, conditions, configprops, flyway, heapdump, health, httptrace, info, jolokia, liquibase, logfile, loggers, mappings, metrics, prometheus, scheduledtasks, sessions, shutdown, threaddump, trace]
spring:
  rabbitmq:
    host: ${evo.spring.rabbitmq.host}
    port: ${evo.spring.rabbitmq.port}
    virtual-host: ${evo.spring.rabbitmq.virtual-host}
    username: ${evo.spring.rabbitmq.username}
    password: ${evo.spring.rabbitmq.password}
  jackson:
    time-zone: GMT+8
  sleuth:
    http:
      enabled: true
    sampler:
      probability: 1.0
    zuul:
      enabled: true
  boot:
    admin:
      client:
        url: ${evo.spring.boot.admin.client.url}
        instance:
          prefer-ip: true
zuul:
  retryable: true
  sensitiveHeaders:
  ignoredServices: '*'
  routes:
    evo-activiti:
      path: /activiti/**
    evo-sp-auth-common:
      path: /auth/common/**
    evo-sp-auth-pc:
      path: /auth/pc/**
    evo-sp-auth-mobile:
      path: /auth/mobile/**
    evo-sp-sys:
      path: /sys/**
    evo-sp-datadict:
      path: /datadict/**
    evo-static-ui:
      path: /static/**
    evo-sp-sys-ui:
      path: /sys-ui/**
    sp-ui: # TODO 兼容 SCFW
      path: /ui/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    evo-activiti:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    evo-sp-auth-common:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    evo-sp-auth-pc:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    evo-sp-auth-mobile:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    evo-sp-sys:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    evo-sp-datadict:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    evo-static-ui:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    evo-sp-sys-ui:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    sp-ui:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
evo-activiti:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
evo-sp-auth-common:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
evo-sp-auth-pc:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
evo-sp-auth-mobile:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
evo-sp-sys:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
evo-sp-datadict:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
evo-static-ui:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
evo-sp-sys-ui:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
sp-ui:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
feign:
  httpclient:
    connection-timeout: 10000
