spring:
  redis:
    cluster:
      nodes: 10.20.133.85:7000, 10.20.133.85:7002, 10.20.133.85:7003, 10.20.133.85:7004, 10.20.133.85:7005
zuul:
  retryable: true
  #ribbon:
  #  eager-load:
  #    enabled: true
  sensitiveHeaders:
  ignoredServices: '*'
  routes:
    sp-auth:
      path: /auth/**
      serviceId: sp-auth
    sp-base:
      path: /base/**
      serviceId: sp-base
    sp-ui:
      path: /ui/**
      serviceId: sp-ui
    sp-eco-base:
      path: /eco/base/**
      serviceId: sp-eco-base
    sp-eco-product:
      path: /eco/prod/**
      serviceId: sp-eco-product
    sp-eco-store:
      path: /eco/store/**
      serviceId: sp-eco-store
    sp-eco-ui:
      path: /eco/ui/**
      serviceId: sp-eco-ui
    sp-eco-ware:
      path: /eco/ware/**
      serviceId: sp-eco-ware
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    sp-auth:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    sp-base:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    sp-ui:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    sp-eco-base:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    sp-eco-product:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    sp-eco-store:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    sp-eco-ui:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    sp-eco-ware:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
feign:
  httpclient:
    connection-timeout: 10000
sp-base:
  ribbon:
    NFLoadBalancerRuleClassName: com.yqjr.scfw.zuul.loadbalancer.BackToSelfRule
sp-ui:
  ribbon:
    NFLoadBalancerRuleClassName: com.yqjr.scfw.zuul.loadbalancer.BackToSelfRule
sp-eco-base:
  ribbon:
    NFLoadBalancerRuleClassName: com.yqjr.scfw.zuul.loadbalancer.BackToSelfRule
sp-eco-product:
  ribbon:
    NFLoadBalancerRuleClassName: com.yqjr.scfw.zuul.loadbalancer.BackToSelfRule
sp-eco-store:
  ribbon:
    NFLoadBalancerRuleClassName: com.yqjr.scfw.zuul.loadbalancer.BackToSelfRule
sp-eco-ui:
  ribbon:
    NFLoadBalancerRuleClassName: com.yqjr.scfw.zuul.loadbalancer.BackToSelfRule
sp-eco-ware:
  ribbon:
    NFLoadBalancerRuleClassName: com.yqjr.scfw.zuul.loadbalancer.BackToSelfRule
