server:
  port: 20010
  tomcat:
    max-threads: 128
    min-spare-threads: 64
spring:
  application:
    name: evo-zuul
  jackson:
    time-zone: GMT+8
zuul:
  retryable: true
  sensitiveHeaders:
  ignoredServices: '*'
  routes:
    evo-activiti:
      path: /activiti/**
    evo-sp-auth-common:
      path: /auth/common/**
    evo-sp-auth-pc:
      path: /auth/pc/**
    evo-sp-auth-mobile:
      path: /auth/mobile/**
    evo-sp-sys:
      path: /sys/**
    evo-sp-datadict:
      path: /datadict/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    evo-activiti:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    evo-sp-auth-common:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    evo-sp-auth-pc:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    evo-sp-auth-mobile:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    evo-sp-sys:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    evo-sp-datadict:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
evo-activiti:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
evo-sp-auth-common:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
evo-sp-auth-pc:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
evo-sp-auth-mobile:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
evo-sp-sys:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
evo-sp-datadict:
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
feign:
  httpclient:
    connection-timeout: 10000
