server:
  port: ${port:20020}
  tomcat:
    max-threads: 128
    min-spare-threads: 64
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
spring:
  datasource:
    url: ${evo.framework.datasource.url}
    username: ${evo.framework.datasource.username}
    password: ${evo.framework.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 30000 # 等待连接池分配连接的最大时长
      idle-timeout: 600000 # 连接闲置状态的最大时长
      maximum-pool-size: 60 # 连接池中允许的最大连接数, 推荐的公式：((core_count * 2) + effective_spindle_count)
      max-lifetime: 1800000 # 连接的生命时长, 建议设置比数据库超时时长少30秒
      minimum-idle: 10
      read-only: false # 连接只读数据库时配置为true, 保证安全
  rabbitmq:
    addresses: ${evo.rabbitmq.addresses}
    host: ${evo.rabbitmq.host}
    port: ${evo.rabbitmq.port}
    virtual-host: ${evo.rabbitmq.virtual-host}
    username: ${evo.rabbitmq.username}
    password: ${evo.rabbitmq.password}
  jackson:
    time-zone: GMT+8
  sleuth:
    http:
      enabled: true
    sampler:
      probability: 1.0
    zuul:
      enabled: true
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
zuul:
  retryable: true
  sensitiveHeaders:
  ignoredServices: '*'
  ribbon:
    eager-load:
      enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 300000
ribbon:
  NFLoadBalancerRuleClassName: ${evo.ribbon.NFLoadBalancerRuleClassName}
  ConnectTimeout: 10000
  ReadTimeout: 30000
  OkToRetryOnAllOperations: false # 重试策略，因为涉及到服务调用幂等性，所以暂时关闭此三个属性
  MaxAutoRetriesNextServer: 0 # 在其他服务器的重试次数
  MaxAutoRetries: 0 # 在相同服务器正常请求之外的重试次数
sp-eco-mobile-car:
  ribbon:
    ReadTimeout: 60000
evo:
  session:
    user-context:
      enabled: false
