server:
  port: ${port:30120}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.144.136:1521:PROD
    username: payment
    password: payment$test
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      maximum-pool-size: 60
      max-lifetime: 1800000
      minimum-idle: 10
      read-only: false
  rabbitmq:
    addresses: ${evo.rabbitmq.addresses}
    host: ${evo.rabbitmq.host}
    port: ${evo.rabbitmq.port}
    virtual-host: ${evo.rabbitmq.virtual-host}
    username: ${evo.rabbitmq.username}
    password: ${evo.rabbitmq.password}
  redis:
    cluster:
      nodes: ${evo.redis.cluster.nodes}
  cache:
    redis:
      time-to-live: 3600s
      use-key-prefix: false
  jackson:
    time-zone: GMT+8
  sleuth:
    http:
      enabled: true
    sampler:
      probability: 1.0
mybatis:
  type-aliases-package: com.github.framework.evo.datadict.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
