server:
  port: 20120
spring:
  datasource:
    url: ${evo.sp.datadict.datasource.url}
    username: ${evo.sp.datadict.datasource.username}
    password: ${evo.sp.datadict.datasource.password}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 600000
      maximum-pool-size: 60
      max-lifetime: 1800000
      minimum-idle: 10
      read-only: false
  rabbitmq:
    host: ${evo.spring.rabbitmq.host}
    port: ${evo.spring.rabbitmq.port}
    virtual-host: ${evo.spring.rabbitmq.virtual-host}
    username: ${evo.spring.rabbitmq.username}
    password: ${evo.spring.rabbitmq.password}
  redis:
    host: ${evo.spring.redis.host}
    cluster:
      nodes: ${evo.spring.redis.cluster.nodes}
    password: ${evo.spring.redis.password}
  cache:
    redis:
      time-to-live: 3600s
      use-key-prefix: false
  jackson:
    time-zone: GMT+8
  sleuth:
    sampler:
      probability: 1.0
mybatis:
  type-aliases-package: com.ritoinfo.framework.evo.sp.datadict.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
