server:
  port: 20110
spring:
  application:
    name: evo-sp-datadict
  redis:
#    cluster:
#      nodes: 10.20.133.85:7000, 10.20.133.85:7002, 10.20.133.85:7003, 10.20.133.85:7004, 10.20.133.85:7005
    host: 127.0.0.1
    password: 123456
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/evo_datadict?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8

mybatis:
  type-aliases-package: com.ritoinfo.framework.evo.sp.datadict.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
