server:
  port: 20105
spring:
  application:
    name: evo-sp-auth-common
  cache:
    redis:
      time-to-live: 3600s
      use-key-prefix: false
  redis:
    host: 127.0.0.1
    password: 123456
  jackson:
    time-zone: GMT+8
  zipkin:
    base-url: http://10.20.133.30:20015
#    discovery-client-enabled: true
#    locator:
#      discovery:
#        enabled: true
  sleuth:
    sampler:
      probability: 1.0
---
spring:
  profiles: sit
  redis:
    cluster:
      nodes: 10.20.133.85:7000, 10.20.133.85:7002, 10.20.133.85:7003, 10.20.133.85:7004, 10.20.133.85:7005
    password:
