jwt:
  algorithm: HS512
  issuer: http://ritoinfo.com
  signingKey: 1580fcb1746e468095b1bc24b6fb94b8
  expirationTime: 60
  refreshExpirationTime: 240
  header: X-Authorization
  headPrefix: 'Bearer '
password:
  salt: 31415926
auth:
  loginPath: /ui/comm/login
  loginAction: /auth/login
  logoutAction: /auth/logout
  failurePath: /ui/comm/login
  excludePaths: ['${auth.loginPath}', '${auth.loginAction}', '${auth.failurePath}', /error,
                  /ui/static/**/*, /ui/common/**/*, /ui/css/**/*, /ui/fonts/**/*, /ui/images/**/*, /ui/img/**/*, /ui/js/**/*,
                  /eco/ui/static/**/*, /eco/ui/common/**/*, /eco/ui/css/**/*, /eco/ui/fonts/**/*, /eco/ui/images/**/*, /eco/ui/img/**/*, /eco/ui/js/**/*]
