jwt:
  signingKey: 1580fcb1746e468065b1bc24b6fb94b8
sms:
  address: http://10.21.111.71:9087/smserver/submitMessage
evo:
  spring:
    redis:
      cluster:
        nodes: 10.20.133.85:7000, 10.20.133.85:7002, 10.20.133.85:7003, 10.20.133.85:7004, 10.20.133.85:7005
    rabbitmq:
      addresses: 10.20.133.43:5672
      host: 10.20.133.43
      port: 5672
      virtual-host: vhost_eco
      username: eco
      password: eco
    boot:
      admin:
        client:
          url: http://10.20.133.30:20020
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
  sp:
    sys:
      datasource:
        url: jdbc:mysql://10.20.133.43:8066/evo_sys?useUnicode=true&characterEncoding=UTF8
        username: evo_sys
        password: evo_sys
    datadict:
      datasource:
        url: jdbc:mysql://10.20.133.43:8066/evo_datadict?useUnicode=true&characterEncoding=UTF8
        username: evo_datadict
        password: evo_datadict
    activiti:
      datasource:
        url: jdbc:mysql://10.20.133.43:8066/evo_activiti?useUnicode=true&characterEncoding=UTF8
        username: evo_activiti
        password: evo_activiti
    eco-mobile-car:
      datasource:
        url: jdbc:mysql://10.20.133.43:8066/eco_mobile?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: eco_mobile
        password: eco_mobile
