jwt:
  signingKey: 1580fcb1746e468096b1bc24b6fb94b8
sms:
  address: http://10.21.111.71:9087/smserver/submitMessage
evo:
  logstash:
    destination: 192.168.1.28:9600
  # eureka 无法在 bootstrap.yml 中配置
  eureka:
    instance:
      ip-address: 192.168.1.24
    client:
      serviceUrl:
        defaultZone: http://192.168.1.24:50101/eureka
  spring:
    redis:
      cluster:
        nodes: 192.168.1.26:7001, 192.168.1.26:7002, 192.168.1.26:7003, 192.168.1.26:7004, 192.168.1.26:7005, 192.168.1.26:7006
    rabbitmq:
      addresses: 192.168.1.27:5672
      host: 192.168.1.27
      port: 5672
      virtual-host: vhost_eco
      username: eco
      password: eco
    boot:
      admin:
        client:
          url: http://192.168.1.24:20020
  ribbon:
    NFLoadBalancerRuleClassName: com.ritoinfo.framework.evo.zuul.loadbalancer.BackToSelfRule
  sp:
    sys:
      datasource:
        url: jdbc:mysql://192.168.1.29:3306/evo_sys?useUnicode=true&characterEncoding=UTF8
        username: evo_sys
        password: evo_sys
    datadict:
      datasource:
        url: jdbc:mysql://192.168.1.29:3306/evo_datadict?useUnicode=true&characterEncoding=UTF8
        username: evo_datadict
        password: evo_datadict
    activiti:
      datasource:
        url: jdbc:mysql://192.168.1.29:3306/evo_activiti?useUnicode=true&characterEncoding=UTF8
        username: evo_activiti
        password: evo_activiti
    eco-mobile-car:
      datasource:
        url: jdbc:mysql://10.20.133.43:8066/eco_mobile?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: eco_mobile
        password: eco_mobile
