server:
  port: 20100
spring:
  application:
    name: evo-sp-sys
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/evo_sys?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 30000 # 等待连接池分配连接的最大时长
      idle-timeout: 600000 # 连接闲置状态的最大时长
      maximum-pool-size: 60 # 连接池中允许的最大连接数, 推荐的公式：((core_count * 2) + effective_spindle_count)
      max-lifetime: 1800000 # 连接的生命时长, 建议设置比数据库超时时长少30秒
      minimum-idle: 10
      read-only: false # 连接只读数据库时配置为true, 保证安全
  jackson:
    time-zone: GMT+8
  zipkin:
    base-url: http://10.20.133.30:20015
#    discovery-client-enabled: true
#    locator:
#      discovery:
#        enabled: true
  sleuth:
    sampler:
      probability: 1.0
mybatis:
  type-aliases-package: com.ritoinfo.framework.evo.sp.sys.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
---
spring:
  profiles: sit
  datasource:
    url: jdbc:mysql://10.20.133.43:8066/evo_sys?useUnicode=true&characterEncoding=UTF8
    username: evo_sys
    password: evo_sys
