server:
  port: ${port:22222}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
spring:
  datasource:
    url: jdbc:oracle:thin:@10.128.23.210:1521:intgbkdb
    username: inthxyw
    password: inthxyw$test
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      #connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 600000
      maximum-pool-size: 60
      max-lifetime: 1800000
      minimum-idle: 10
      read-only: false
  rabbitmq:
    #addresses: ${evo.rabbitmq.addresses}
    host: ${evo.rabbitmq.ip}
    port: ${evo.rabbitmq.port}
    virtual-host: ${evo.rabbitmq.virtualBox}
    username: ${evo.rabbitmq.username}
    password: ${evo.rabbitmq.password}
  jackson:
    time-zone: GMT+8
  sleuth:
    http:
      enabled: true
    sampler:
      probability: 1.0
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: 'null'
  global-config:
    refresh: ${mybatis.global.refresh}